/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebServiceOrderStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebServiceOrderStatusTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebServiceOrderStatus
        //private TsiWebServiceOrderStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebServiceOrderStatus
            //instance = new TsiWebServiceOrderStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebServiceOrderStatus
        /// </summary>
        [TestMethod]
        public void TsiWebServiceOrderStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebServiceOrderStatus
            //Assert.IsInstanceOfType<TsiWebServiceOrderStatus> (instance, "variable 'instance' is a TsiWebServiceOrderStatus");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [TestMethod]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TicketChange'
        /// </summary>
        [TestMethod]
        public void TicketChangeTest()
        {
            // TODO unit test for the property 'TicketChange'
        }
        /// <summary>
        /// Test the property 'IVRID'
        /// </summary>
        [TestMethod]
        public void IVRIDTest()
        {
            // TODO unit test for the property 'IVRID'
        }
        /// <summary>
        /// Test the property 'SystemEntry'
        /// </summary>
        [TestMethod]
        public void SystemEntryTest()
        {
            // TODO unit test for the property 'SystemEntry'
        }
        /// <summary>
        /// Test the property 'SystemDefault'
        /// </summary>
        [TestMethod]
        public void SystemDefaultTest()
        {
            // TODO unit test for the property 'SystemDefault'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [TestMethod]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [TestMethod]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

    }

}
