/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdateServiceOrderModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdateServiceOrderModelTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdateServiceOrderModel
        //private TsiWebUpdateServiceOrderModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdateServiceOrderModel
            //instance = new TsiWebUpdateServiceOrderModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdateServiceOrderModel
        /// </summary>
        [TestMethod]
        public void TsiWebUpdateServiceOrderModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdateServiceOrderModel
            //Assert.IsInstanceOfType<TsiWebUpdateServiceOrderModel> (instance, "variable 'instance' is a TsiWebUpdateServiceOrderModel");
        }


        /// <summary>
        /// Test the property 'DiscountType'
        /// </summary>
        [TestMethod]
        public void DiscountTypeTest()
        {
            // TODO unit test for the property 'DiscountType'
        }
        /// <summary>
        /// Test the property 'DiscountPercent'
        /// </summary>
        [TestMethod]
        public void DiscountPercentTest()
        {
            // TODO unit test for the property 'DiscountPercent'
        }
        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [TestMethod]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }
        /// <summary>
        /// Test the property 'DiscountSellForPrice'
        /// </summary>
        [TestMethod]
        public void DiscountSellForPriceTest()
        {
            // TODO unit test for the property 'DiscountSellForPrice'
        }
        /// <summary>
        /// Test the property 'DiscountMarginPercent'
        /// </summary>
        [TestMethod]
        public void DiscountMarginPercentTest()
        {
            // TODO unit test for the property 'DiscountMarginPercent'
        }
        /// <summary>
        /// Test the property 'CompleteOpenTasks'
        /// </summary>
        [TestMethod]
        public void CompleteOpenTasksTest()
        {
            // TODO unit test for the property 'CompleteOpenTasks'
        }
        /// <summary>
        /// Test the property 'ContactNumber'
        /// </summary>
        [TestMethod]
        public void ContactNumberTest()
        {
            // TODO unit test for the property 'ContactNumber'
        }
        /// <summary>
        /// Test the property 'TechnicianAssigned'
        /// </summary>
        [TestMethod]
        public void TechnicianAssignedTest()
        {
            // TODO unit test for the property 'TechnicianAssigned'
        }
        /// <summary>
        /// Test the property 'EstimatedHours'
        /// </summary>
        [TestMethod]
        public void EstimatedHoursTest()
        {
            // TODO unit test for the property 'EstimatedHours'
        }
        /// <summary>
        /// Test the property 'EstimatedMinutes'
        /// </summary>
        [TestMethod]
        public void EstimatedMinutesTest()
        {
            // TODO unit test for the property 'EstimatedMinutes'
        }
        /// <summary>
        /// Test the property 'CallBackCount'
        /// </summary>
        [TestMethod]
        public void CallBackCountTest()
        {
            // TODO unit test for the property 'CallBackCount'
        }
        /// <summary>
        /// Test the property 'RepToCredit'
        /// </summary>
        [TestMethod]
        public void RepToCreditTest()
        {
            // TODO unit test for the property 'RepToCredit'
        }
        /// <summary>
        /// Test the property 'ContractNumber'
        /// </summary>
        [TestMethod]
        public void ContractNumberTest()
        {
            // TODO unit test for the property 'ContractNumber'
        }
        /// <summary>
        /// Test the property 'TakenBy'
        /// </summary>
        [TestMethod]
        public void TakenByTest()
        {
            // TODO unit test for the property 'TakenBy'
        }
        /// <summary>
        /// Test the property 'DispatchBoardNumber'
        /// </summary>
        [TestMethod]
        public void DispatchBoardNumberTest()
        {
            // TODO unit test for the property 'DispatchBoardNumber'
        }
        /// <summary>
        /// Test the property 'PayMethodsId'
        /// </summary>
        [TestMethod]
        public void PayMethodsIdTest()
        {
            // TODO unit test for the property 'PayMethodsId'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [TestMethod]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'AlternatePhoneNumber'
        /// </summary>
        [TestMethod]
        public void AlternatePhoneNumberTest()
        {
            // TODO unit test for the property 'AlternatePhoneNumber'
        }
        /// <summary>
        /// Test the property 'AlternatePhoneLocation'
        /// </summary>
        [TestMethod]
        public void AlternatePhoneLocationTest()
        {
            // TODO unit test for the property 'AlternatePhoneLocation'
        }
        /// <summary>
        /// Test the property 'AlternateContactEmailAddress'
        /// </summary>
        [TestMethod]
        public void AlternateContactEmailAddressTest()
        {
            // TODO unit test for the property 'AlternateContactEmailAddress'
        }
        /// <summary>
        /// Test the property 'AlternateContactPhoneNumber'
        /// </summary>
        [TestMethod]
        public void AlternateContactPhoneNumberTest()
        {
            // TODO unit test for the property 'AlternateContactPhoneNumber'
        }
        /// <summary>
        /// Test the property 'AlternateContactPhoneLocation'
        /// </summary>
        [TestMethod]
        public void AlternateContactPhoneLocationTest()
        {
            // TODO unit test for the property 'AlternateContactPhoneLocation'
        }
        /// <summary>
        /// Test the property 'BriefDescription'
        /// </summary>
        [TestMethod]
        public void BriefDescriptionTest()
        {
            // TODO unit test for the property 'BriefDescription'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [TestMethod]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [TestMethod]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [TestMethod]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ServiceOrderType'
        /// </summary>
        [TestMethod]
        public void ServiceOrderTypeTest()
        {
            // TODO unit test for the property 'ServiceOrderType'
        }
        /// <summary>
        /// Test the property 'System'
        /// </summary>
        [TestMethod]
        public void SystemTest()
        {
            // TODO unit test for the property 'System'
        }
        /// <summary>
        /// Test the property 'WorkRequested'
        /// </summary>
        [TestMethod]
        public void WorkRequestedTest()
        {
            // TODO unit test for the property 'WorkRequested'
        }
        /// <summary>
        /// Test the property 'WorkPerformed'
        /// </summary>
        [TestMethod]
        public void WorkPerformedTest()
        {
            // TODO unit test for the property 'WorkPerformed'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [TestMethod]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'ShippingMethod'
        /// </summary>
        [TestMethod]
        public void ShippingMethodTest()
        {
            // TODO unit test for the property 'ShippingMethod'
        }
        /// <summary>
        /// Test the property 'InternalComments'
        /// </summary>
        [TestMethod]
        public void InternalCommentsTest()
        {
            // TODO unit test for the property 'InternalComments'
        }
        /// <summary>
        /// Test the property 'DirectionsToLocation'
        /// </summary>
        [TestMethod]
        public void DirectionsToLocationTest()
        {
            // TODO unit test for the property 'DirectionsToLocation'
        }
        /// <summary>
        /// Test the property 'CustomerPurchaseOrder'
        /// </summary>
        [TestMethod]
        public void CustomerPurchaseOrderTest()
        {
            // TODO unit test for the property 'CustomerPurchaseOrder'
        }
        /// <summary>
        /// Test the property 'VerifiedBy'
        /// </summary>
        [TestMethod]
        public void VerifiedByTest()
        {
            // TODO unit test for the property 'VerifiedBy'
        }
        /// <summary>
        /// Test the property 'ServiceZone'
        /// </summary>
        [TestMethod]
        public void ServiceZoneTest()
        {
            // TODO unit test for the property 'ServiceZone'
        }
        /// <summary>
        /// Test the property 'RequestedBy'
        /// </summary>
        [TestMethod]
        public void RequestedByTest()
        {
            // TODO unit test for the property 'RequestedBy'
        }
        /// <summary>
        /// Test the property 'TagNumber'
        /// </summary>
        [TestMethod]
        public void TagNumberTest()
        {
            // TODO unit test for the property 'TagNumber'
        }
        /// <summary>
        /// Test the property 'LoanAgreement'
        /// </summary>
        [TestMethod]
        public void LoanAgreementTest()
        {
            // TODO unit test for the property 'LoanAgreement'
        }
        /// <summary>
        /// Test the property 'DebitCreditMemo'
        /// </summary>
        [TestMethod]
        public void DebitCreditMemoTest()
        {
            // TODO unit test for the property 'DebitCreditMemo'
        }
        /// <summary>
        /// Test the property 'InvoiceTerms'
        /// </summary>
        [TestMethod]
        public void InvoiceTermsTest()
        {
            // TODO unit test for the property 'InvoiceTerms'
        }
        /// <summary>
        /// Test the property 'FreightTerms'
        /// </summary>
        [TestMethod]
        public void FreightTermsTest()
        {
            // TODO unit test for the property 'FreightTerms'
        }
        /// <summary>
        /// Test the property 'SalesTaxCode'
        /// </summary>
        [TestMethod]
        public void SalesTaxCodeTest()
        {
            // TODO unit test for the property 'SalesTaxCode'
        }
        /// <summary>
        /// Test the property 'DateTimeReceived'
        /// </summary>
        [TestMethod]
        public void DateTimeReceivedTest()
        {
            // TODO unit test for the property 'DateTimeReceived'
        }
        /// <summary>
        /// Test the property 'DateTimeRequested'
        /// </summary>
        [TestMethod]
        public void DateTimeRequestedTest()
        {
            // TODO unit test for the property 'DateTimeRequested'
        }
        /// <summary>
        /// Test the property 'DateTimeOpened'
        /// </summary>
        [TestMethod]
        public void DateTimeOpenedTest()
        {
            // TODO unit test for the property 'DateTimeOpened'
        }
        /// <summary>
        /// Test the property 'DateTimeClosed'
        /// </summary>
        [TestMethod]
        public void DateTimeClosedTest()
        {
            // TODO unit test for the property 'DateTimeClosed'
        }
        /// <summary>
        /// Test the property 'VerifiedDate'
        /// </summary>
        [TestMethod]
        public void VerifiedDateTest()
        {
            // TODO unit test for the property 'VerifiedDate'
        }
        /// <summary>
        /// Test the property 'ResolvedOnPhone'
        /// </summary>
        [TestMethod]
        public void ResolvedOnPhoneTest()
        {
            // TODO unit test for the property 'ResolvedOnPhone'
        }
        /// <summary>
        /// Test the property 'BidPrice'
        /// </summary>
        [TestMethod]
        public void BidPriceTest()
        {
            // TODO unit test for the property 'BidPrice'
        }
        /// <summary>
        /// Test the property 'TradeIn'
        /// </summary>
        [TestMethod]
        public void TradeInTest()
        {
            // TODO unit test for the property 'TradeIn'
        }
        /// <summary>
        /// Test the property 'Deposit'
        /// </summary>
        [TestMethod]
        public void DepositTest()
        {
            // TODO unit test for the property 'Deposit'
        }
        /// <summary>
        /// Test the property 'Freight'
        /// </summary>
        [TestMethod]
        public void FreightTest()
        {
            // TODO unit test for the property 'Freight'
        }
        /// <summary>
        /// Test the property 'BillToAddressType'
        /// </summary>
        [TestMethod]
        public void BillToAddressTypeTest()
        {
            // TODO unit test for the property 'BillToAddressType'
        }
        /// <summary>
        /// Test the property 'BillToAddressAccountNumber'
        /// </summary>
        [TestMethod]
        public void BillToAddressAccountNumberTest()
        {
            // TODO unit test for the property 'BillToAddressAccountNumber'
        }
        /// <summary>
        /// Test the property 'BillTo'
        /// </summary>
        [TestMethod]
        public void BillToTest()
        {
            // TODO unit test for the property 'BillTo'
        }
        /// <summary>
        /// Test the property 'ShipToAddressType'
        /// </summary>
        [TestMethod]
        public void ShipToAddressTypeTest()
        {
            // TODO unit test for the property 'ShipToAddressType'
        }
        /// <summary>
        /// Test the property 'ShipToAddressAccountNumber'
        /// </summary>
        [TestMethod]
        public void ShipToAddressAccountNumberTest()
        {
            // TODO unit test for the property 'ShipToAddressAccountNumber'
        }
        /// <summary>
        /// Test the property 'ShipTo'
        /// </summary>
        [TestMethod]
        public void ShipToTest()
        {
            // TODO unit test for the property 'ShipTo'
        }
        /// <summary>
        /// Test the property 'UseAlternateShipToTaxCode'
        /// </summary>
        [TestMethod]
        public void UseAlternateShipToTaxCodeTest()
        {
            // TODO unit test for the property 'UseAlternateShipToTaxCode'
        }
        /// <summary>
        /// Test the property 'CanReassignToHourlyUsageContractAlreadyInvoiced'
        /// </summary>
        [TestMethod]
        public void CanReassignToHourlyUsageContractAlreadyInvoicedTest()
        {
            // TODO unit test for the property 'CanReassignToHourlyUsageContractAlreadyInvoiced'
        }
        /// <summary>
        /// Test the property 'CanUpdateContractMeterReadingToServiceOrderReading'
        /// </summary>
        [TestMethod]
        public void CanUpdateContractMeterReadingToServiceOrderReadingTest()
        {
            // TODO unit test for the property 'CanUpdateContractMeterReadingToServiceOrderReading'
        }
        /// <summary>
        /// Test the property 'AllowInactiveContract'
        /// </summary>
        [TestMethod]
        public void AllowInactiveContractTest()
        {
            // TODO unit test for the property 'AllowInactiveContract'
        }
        /// <summary>
        /// Test the property 'AllowFutureContract'
        /// </summary>
        [TestMethod]
        public void AllowFutureContractTest()
        {
            // TODO unit test for the property 'AllowFutureContract'
        }
        /// <summary>
        /// Test the property 'AllowContractNoRemaining'
        /// </summary>
        [TestMethod]
        public void AllowContractNoRemainingTest()
        {
            // TODO unit test for the property 'AllowContractNoRemaining'
        }
        /// <summary>
        /// Test the property 'UseContractDefaultTech'
        /// </summary>
        [TestMethod]
        public void UseContractDefaultTechTest()
        {
            // TODO unit test for the property 'UseContractDefaultTech'
        }
        /// <summary>
        /// Test the property 'DisplayOnCustomerPortal'
        /// </summary>
        [TestMethod]
        public void DisplayOnCustomerPortalTest()
        {
            // TODO unit test for the property 'DisplayOnCustomerPortal'
        }

    }

}
