/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebContractSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebContractSummaryTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebContractSummary
        //private TsiWebContractSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebContractSummary
            //instance = new TsiWebContractSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebContractSummary
        /// </summary>
        [TestMethod]
        public void TsiWebContractSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebContractSummary
            //Assert.IsInstanceOfType<TsiWebContractSummary> (instance, "variable 'instance' is a TsiWebContractSummary");
        }


        /// <summary>
        /// Test the property 'ContractNumber'
        /// </summary>
        [TestMethod]
        public void ContractNumberTest()
        {
            // TODO unit test for the property 'ContractNumber'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [TestMethod]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'CreatedByRepName'
        /// </summary>
        [TestMethod]
        public void CreatedByRepNameTest()
        {
            // TODO unit test for the property 'CreatedByRepName'
        }
        /// <summary>
        /// Test the property 'CreatedByRepEmailAddress'
        /// </summary>
        [TestMethod]
        public void CreatedByRepEmailAddressTest()
        {
            // TODO unit test for the property 'CreatedByRepEmailAddress'
        }
        /// <summary>
        /// Test the property 'CreatedByRepPhoneNumber'
        /// </summary>
        [TestMethod]
        public void CreatedByRepPhoneNumberTest()
        {
            // TODO unit test for the property 'CreatedByRepPhoneNumber'
        }
        /// <summary>
        /// Test the property 'AssignedTechRepName'
        /// </summary>
        [TestMethod]
        public void AssignedTechRepNameTest()
        {
            // TODO unit test for the property 'AssignedTechRepName'
        }
        /// <summary>
        /// Test the property 'AssignedTechRepEmailAddress'
        /// </summary>
        [TestMethod]
        public void AssignedTechRepEmailAddressTest()
        {
            // TODO unit test for the property 'AssignedTechRepEmailAddress'
        }
        /// <summary>
        /// Test the property 'AssignedTechRepPhoneNumber'
        /// </summary>
        [TestMethod]
        public void AssignedTechRepPhoneNumberTest()
        {
            // TODO unit test for the property 'AssignedTechRepPhoneNumber'
        }
        /// <summary>
        /// Test the property 'RepToCreditName'
        /// </summary>
        [TestMethod]
        public void RepToCreditNameTest()
        {
            // TODO unit test for the property 'RepToCreditName'
        }
        /// <summary>
        /// Test the property 'RepToCreditEmailAddress'
        /// </summary>
        [TestMethod]
        public void RepToCreditEmailAddressTest()
        {
            // TODO unit test for the property 'RepToCreditEmailAddress'
        }
        /// <summary>
        /// Test the property 'RepToCreditPhoneNumber'
        /// </summary>
        [TestMethod]
        public void RepToCreditPhoneNumberTest()
        {
            // TODO unit test for the property 'RepToCreditPhoneNumber'
        }
        /// <summary>
        /// Test the property 'ContractAccount'
        /// </summary>
        [TestMethod]
        public void ContractAccountTest()
        {
            // TODO unit test for the property 'ContractAccount'
        }
        /// <summary>
        /// Test the property 'ItemsCovered'
        /// </summary>
        [TestMethod]
        public void ItemsCoveredTest()
        {
            // TODO unit test for the property 'ItemsCovered'
        }

    }

}
