/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebEmailAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebEmailAddressTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebEmailAddress
        //private TsiWebEmailAddress instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebEmailAddress
            //instance = new TsiWebEmailAddress();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebEmailAddress
        /// </summary>
        [TestMethod]
        public void TsiWebEmailAddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebEmailAddress
            //Assert.IsInstanceOfType<TsiWebEmailAddress> (instance, "variable 'instance' is a TsiWebEmailAddress");
        }


        /// <summary>
        /// Test the property 'EmailAddressId'
        /// </summary>
        [TestMethod]
        public void EmailAddressIdTest()
        {
            // TODO unit test for the property 'EmailAddressId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [TestMethod]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [TestMethod]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DoNotEmail'
        /// </summary>
        [TestMethod]
        public void DoNotEmailTest()
        {
            // TODO unit test for the property 'DoNotEmail'
        }
        /// <summary>
        /// Test the property 'IsPrimary'
        /// </summary>
        [TestMethod]
        public void IsPrimaryTest()
        {
            // TODO unit test for the property 'IsPrimary'
        }

    }

}
