/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebContractDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebContractDetailTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebContractDetail
        //private TsiWebContractDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebContractDetail
            //instance = new TsiWebContractDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebContractDetail
        /// </summary>
        [TestMethod]
        public void TsiWebContractDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebContractDetail
            //Assert.IsInstanceOfType<TsiWebContractDetail> (instance, "variable 'instance' is a TsiWebContractDetail");
        }


        /// <summary>
        /// Test the property 'ContractNumber'
        /// </summary>
        [TestMethod]
        public void ContractNumberTest()
        {
            // TODO unit test for the property 'ContractNumber'
        }
        /// <summary>
        /// Test the property 'ContractAccount'
        /// </summary>
        [TestMethod]
        public void ContractAccountTest()
        {
            // TODO unit test for the property 'ContractAccount'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [TestMethod]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'CreatedByRep'
        /// </summary>
        [TestMethod]
        public void CreatedByRepTest()
        {
            // TODO unit test for the property 'CreatedByRep'
        }
        /// <summary>
        /// Test the property 'AssignedTechRep'
        /// </summary>
        [TestMethod]
        public void AssignedTechRepTest()
        {
            // TODO unit test for the property 'AssignedTechRep'
        }
        /// <summary>
        /// Test the property 'RepToCredit'
        /// </summary>
        [TestMethod]
        public void RepToCreditTest()
        {
            // TODO unit test for the property 'RepToCredit'
        }
        /// <summary>
        /// Test the property 'ItemsCovered'
        /// </summary>
        [TestMethod]
        public void ItemsCoveredTest()
        {
            // TODO unit test for the property 'ItemsCovered'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [TestMethod]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

    }

}
