/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebServiceOrderSystem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebServiceOrderSystemTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebServiceOrderSystem
        //private TsiWebServiceOrderSystem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebServiceOrderSystem
            //instance = new TsiWebServiceOrderSystem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebServiceOrderSystem
        /// </summary>
        [TestMethod]
        public void TsiWebServiceOrderSystemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebServiceOrderSystem
            //Assert.IsInstanceOfType<TsiWebServiceOrderSystem> (instance, "variable 'instance' is a TsiWebServiceOrderSystem");
        }


        /// <summary>
        /// Test the property 'TechSkillLevel'
        /// </summary>
        [TestMethod]
        public void TechSkillLevelTest()
        {
            // TODO unit test for the property 'TechSkillLevel'
        }
        /// <summary>
        /// Test the property 'Skill'
        /// </summary>
        [TestMethod]
        public void SkillTest()
        {
            // TODO unit test for the property 'Skill'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [TestMethod]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'SystemType'
        /// </summary>
        [TestMethod]
        public void SystemTypeTest()
        {
            // TODO unit test for the property 'SystemType'
        }
        /// <summary>
        /// Test the property 'RepGroupForSystem'
        /// </summary>
        [TestMethod]
        public void RepGroupForSystemTest()
        {
            // TODO unit test for the property 'RepGroupForSystem'
        }

    }

}
