/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdatePurchaseOrderModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdatePurchaseOrderModelTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdatePurchaseOrderModel
        //private TsiWebUpdatePurchaseOrderModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdatePurchaseOrderModel
            //instance = new TsiWebUpdatePurchaseOrderModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdatePurchaseOrderModel
        /// </summary>
        [TestMethod]
        public void TsiWebUpdatePurchaseOrderModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdatePurchaseOrderModel
            //Assert.IsInstanceOfType<TsiWebUpdatePurchaseOrderModel> (instance, "variable 'instance' is a TsiWebUpdatePurchaseOrderModel");
        }


        /// <summary>
        /// Test the property 'PurchaseOrderCostToUseType'
        /// </summary>
        [TestMethod]
        public void PurchaseOrderCostToUseTypeTest()
        {
            // TODO unit test for the property 'PurchaseOrderCostToUseType'
        }
        /// <summary>
        /// Test the property 'VendorAccountNumber'
        /// </summary>
        [TestMethod]
        public void VendorAccountNumberTest()
        {
            // TODO unit test for the property 'VendorAccountNumber'
        }
        /// <summary>
        /// Test the property 'DefaultReceivingBin'
        /// </summary>
        [TestMethod]
        public void DefaultReceivingBinTest()
        {
            // TODO unit test for the property 'DefaultReceivingBin'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [TestMethod]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [TestMethod]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderDate'
        /// </summary>
        [TestMethod]
        public void PurchaseOrderDateTest()
        {
            // TODO unit test for the property 'PurchaseOrderDate'
        }
        /// <summary>
        /// Test the property 'ConfirmedBy'
        /// </summary>
        [TestMethod]
        public void ConfirmedByTest()
        {
            // TODO unit test for the property 'ConfirmedBy'
        }
        /// <summary>
        /// Test the property 'ConfirmedDate'
        /// </summary>
        [TestMethod]
        public void ConfirmedDateTest()
        {
            // TODO unit test for the property 'ConfirmedDate'
        }
        /// <summary>
        /// Test the property 'BuyingRepNumber'
        /// </summary>
        [TestMethod]
        public void BuyingRepNumberTest()
        {
            // TODO unit test for the property 'BuyingRepNumber'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [TestMethod]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'OrderTerms'
        /// </summary>
        [TestMethod]
        public void OrderTermsTest()
        {
            // TODO unit test for the property 'OrderTerms'
        }
        /// <summary>
        /// Test the property 'FreightTerms'
        /// </summary>
        [TestMethod]
        public void FreightTermsTest()
        {
            // TODO unit test for the property 'FreightTerms'
        }
        /// <summary>
        /// Test the property 'ShippingMethod'
        /// </summary>
        [TestMethod]
        public void ShippingMethodTest()
        {
            // TODO unit test for the property 'ShippingMethod'
        }
        /// <summary>
        /// Test the property 'UpdateLatestCost'
        /// </summary>
        [TestMethod]
        public void UpdateLatestCostTest()
        {
            // TODO unit test for the property 'UpdateLatestCost'
        }
        /// <summary>
        /// Test the property 'AllowBackOrders'
        /// </summary>
        [TestMethod]
        public void AllowBackOrdersTest()
        {
            // TODO unit test for the property 'AllowBackOrders'
        }
        /// <summary>
        /// Test the property 'ExpectedDate'
        /// </summary>
        [TestMethod]
        public void ExpectedDateTest()
        {
            // TODO unit test for the property 'ExpectedDate'
        }
        /// <summary>
        /// Test the property 'DefaultReceivingLocation'
        /// </summary>
        [TestMethod]
        public void DefaultReceivingLocationTest()
        {
            // TODO unit test for the property 'DefaultReceivingLocation'
        }
        /// <summary>
        /// Test the property 'InvoiceTerms'
        /// </summary>
        [TestMethod]
        public void InvoiceTermsTest()
        {
            // TODO unit test for the property 'InvoiceTerms'
        }
        /// <summary>
        /// Test the property 'Freight'
        /// </summary>
        [TestMethod]
        public void FreightTest()
        {
            // TODO unit test for the property 'Freight'
        }
        /// <summary>
        /// Test the property 'BlindShip'
        /// </summary>
        [TestMethod]
        public void BlindShipTest()
        {
            // TODO unit test for the property 'BlindShip'
        }
        /// <summary>
        /// Test the property 'OrderIdentificationNumber'
        /// </summary>
        [TestMethod]
        public void OrderIdentificationNumberTest()
        {
            // TODO unit test for the property 'OrderIdentificationNumber'
        }
        /// <summary>
        /// Test the property 'TrackingNumber'
        /// </summary>
        [TestMethod]
        public void TrackingNumberTest()
        {
            // TODO unit test for the property 'TrackingNumber'
        }
        /// <summary>
        /// Test the property 'RequestedRepNumber'
        /// </summary>
        [TestMethod]
        public void RequestedRepNumberTest()
        {
            // TODO unit test for the property 'RequestedRepNumber'
        }
        /// <summary>
        /// Test the property 'LinkAccountNumber'
        /// </summary>
        [TestMethod]
        public void LinkAccountNumberTest()
        {
            // TODO unit test for the property 'LinkAccountNumber'
        }
        /// <summary>
        /// Test the property 'LinkQuoteNumber'
        /// </summary>
        [TestMethod]
        public void LinkQuoteNumberTest()
        {
            // TODO unit test for the property 'LinkQuoteNumber'
        }
        /// <summary>
        /// Test the property 'LinkServiceOrderNumber'
        /// </summary>
        [TestMethod]
        public void LinkServiceOrderNumberTest()
        {
            // TODO unit test for the property 'LinkServiceOrderNumber'
        }
        /// <summary>
        /// Test the property 'PaidInFull'
        /// </summary>
        [TestMethod]
        public void PaidInFullTest()
        {
            // TODO unit test for the property 'PaidInFull'
        }
        /// <summary>
        /// Test the property 'InternalComments'
        /// </summary>
        [TestMethod]
        public void InternalCommentsTest()
        {
            // TODO unit test for the property 'InternalComments'
        }
        /// <summary>
        /// Test the property 'Shipper'
        /// </summary>
        [TestMethod]
        public void ShipperTest()
        {
            // TODO unit test for the property 'Shipper'
        }
        /// <summary>
        /// Test the property 'ShipToAddressType'
        /// </summary>
        [TestMethod]
        public void ShipToAddressTypeTest()
        {
            // TODO unit test for the property 'ShipToAddressType'
        }
        /// <summary>
        /// Test the property 'ShipToAddressAccountNumber'
        /// </summary>
        [TestMethod]
        public void ShipToAddressAccountNumberTest()
        {
            // TODO unit test for the property 'ShipToAddressAccountNumber'
        }
        /// <summary>
        /// Test the property 'AlternateShipToAddressID'
        /// </summary>
        [TestMethod]
        public void AlternateShipToAddressIDTest()
        {
            // TODO unit test for the property 'AlternateShipToAddressID'
        }
        /// <summary>
        /// Test the property 'ShipTo'
        /// </summary>
        [TestMethod]
        public void ShipToTest()
        {
            // TODO unit test for the property 'ShipTo'
        }
        /// <summary>
        /// Test the property 'BillToAddressType'
        /// </summary>
        [TestMethod]
        public void BillToAddressTypeTest()
        {
            // TODO unit test for the property 'BillToAddressType'
        }
        /// <summary>
        /// Test the property 'BillToAddressAccountNumber'
        /// </summary>
        [TestMethod]
        public void BillToAddressAccountNumberTest()
        {
            // TODO unit test for the property 'BillToAddressAccountNumber'
        }
        /// <summary>
        /// Test the property 'AlternateBillToAddressID'
        /// </summary>
        [TestMethod]
        public void AlternateBillToAddressIDTest()
        {
            // TODO unit test for the property 'AlternateBillToAddressID'
        }
        /// <summary>
        /// Test the property 'BillTo'
        /// </summary>
        [TestMethod]
        public void BillToTest()
        {
            // TODO unit test for the property 'BillTo'
        }

    }

}
