/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebAccountProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebAccountProfileTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebAccountProfile
        //private TsiWebAccountProfile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebAccountProfile
            //instance = new TsiWebAccountProfile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebAccountProfile
        /// </summary>
        [TestMethod]
        public void TsiWebAccountProfileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebAccountProfile
            //Assert.IsInstanceOfType<TsiWebAccountProfile> (instance, "variable 'instance' is a TsiWebAccountProfile");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [TestMethod]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [TestMethod]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'IsSystemEntry'
        /// </summary>
        [TestMethod]
        public void IsSystemEntryTest()
        {
            // TODO unit test for the property 'IsSystemEntry'
        }
        /// <summary>
        /// Test the property 'IsSystemDefault'
        /// </summary>
        [TestMethod]
        public void IsSystemDefaultTest()
        {
            // TODO unit test for the property 'IsSystemDefault'
        }

    }

}
