/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdateEntryModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdateEntryModelTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdateEntryModel
        //private TsiWebUpdateEntryModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdateEntryModel
            //instance = new TsiWebUpdateEntryModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdateEntryModel
        /// </summary>
        [TestMethod]
        public void TsiWebUpdateEntryModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdateEntryModel
            //Assert.IsInstanceOfType<TsiWebUpdateEntryModel> (instance, "variable 'instance' is a TsiWebUpdateEntryModel");
        }


        /// <summary>
        /// Test the property 'ExistingValue'
        /// </summary>
        [TestMethod]
        public void ExistingValueTest()
        {
            // TODO unit test for the property 'ExistingValue'
        }
        /// <summary>
        /// Test the property 'NewValue'
        /// </summary>
        [TestMethod]
        public void NewValueTest()
        {
            // TODO unit test for the property 'NewValue'
        }

    }

}
