/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPriceBookItemResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPriceBookItemResponseTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPriceBookItemResponse
        //private TsiWebPriceBookItemResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPriceBookItemResponse
            //instance = new TsiWebPriceBookItemResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPriceBookItemResponse
        /// </summary>
        [TestMethod]
        public void TsiWebPriceBookItemResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPriceBookItemResponse
            //Assert.IsInstanceOfType<TsiWebPriceBookItemResponse> (instance, "variable 'instance' is a TsiWebPriceBookItemResponse");
        }


        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [TestMethod]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [TestMethod]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [TestMethod]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
