/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebAccountServiceDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebAccountServiceDetailTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebAccountServiceDetail
        //private TsiWebAccountServiceDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebAccountServiceDetail
            //instance = new TsiWebAccountServiceDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebAccountServiceDetail
        /// </summary>
        [TestMethod]
        public void TsiWebAccountServiceDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebAccountServiceDetail
            //Assert.IsInstanceOfType<TsiWebAccountServiceDetail> (instance, "variable 'instance' is a TsiWebAccountServiceDetail");
        }


        /// <summary>
        /// Test the property 'ServiceZone'
        /// </summary>
        [TestMethod]
        public void ServiceZoneTest()
        {
            // TODO unit test for the property 'ServiceZone'
        }
        /// <summary>
        /// Test the property 'DefaultSystem'
        /// </summary>
        [TestMethod]
        public void DefaultSystemTest()
        {
            // TODO unit test for the property 'DefaultSystem'
        }
        /// <summary>
        /// Test the property 'DefaultDispatchBoardId'
        /// </summary>
        [TestMethod]
        public void DefaultDispatchBoardIdTest()
        {
            // TODO unit test for the property 'DefaultDispatchBoardId'
        }
        /// <summary>
        /// Test the property 'DefaultContractId'
        /// </summary>
        [TestMethod]
        public void DefaultContractIdTest()
        {
            // TODO unit test for the property 'DefaultContractId'
        }
        /// <summary>
        /// Test the property 'DefaultSubContractorId'
        /// </summary>
        [TestMethod]
        public void DefaultSubContractorIdTest()
        {
            // TODO unit test for the property 'DefaultSubContractorId'
        }
        /// <summary>
        /// Test the property 'DefaultServiceTechId'
        /// </summary>
        [TestMethod]
        public void DefaultServiceTechIdTest()
        {
            // TODO unit test for the property 'DefaultServiceTechId'
        }

    }

}
