/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebQuoteOpportunity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebQuoteOpportunityTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebQuoteOpportunity
        //private TsiWebQuoteOpportunity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebQuoteOpportunity
            //instance = new TsiWebQuoteOpportunity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebQuoteOpportunity
        /// </summary>
        [TestMethod]
        public void TsiWebQuoteOpportunityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebQuoteOpportunity
            //Assert.IsInstanceOfType<TsiWebQuoteOpportunity> (instance, "variable 'instance' is a TsiWebQuoteOpportunity");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [TestMethod]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [TestMethod]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ExpectedAmount'
        /// </summary>
        [TestMethod]
        public void ExpectedAmountTest()
        {
            // TODO unit test for the property 'ExpectedAmount'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [TestMethod]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'EstimatedCloseDate'
        /// </summary>
        [TestMethod]
        public void EstimatedCloseDateTest()
        {
            // TODO unit test for the property 'EstimatedCloseDate'
        }
        /// <summary>
        /// Test the property 'StageDescription'
        /// </summary>
        [TestMethod]
        public void StageDescriptionTest()
        {
            // TODO unit test for the property 'StageDescription'
        }
        /// <summary>
        /// Test the property 'ProbabilityPercent'
        /// </summary>
        [TestMethod]
        public void ProbabilityPercentTest()
        {
            // TODO unit test for the property 'ProbabilityPercent'
        }

    }

}
