/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModelTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel
        //private TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel
            //instance = new TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel
        /// </summary>
        [TestMethod]
        public void TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel
            //Assert.IsInstanceOfType<TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel> (instance, "variable 'instance' is a TsiWebUpdateServiceOrderPartsUsedAssemblyDetailModel");
        }


        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [TestMethod]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'SellingPrice'
        /// </summary>
        [TestMethod]
        public void SellingPriceTest()
        {
            // TODO unit test for the property 'SellingPrice'
        }
        /// <summary>
        /// Test the property 'PrintOnInvoice'
        /// </summary>
        [TestMethod]
        public void PrintOnInvoiceTest()
        {
            // TODO unit test for the property 'PrintOnInvoice'
        }
        /// <summary>
        /// Test the property 'OrderByDate'
        /// </summary>
        [TestMethod]
        public void OrderByDateTest()
        {
            // TODO unit test for the property 'OrderByDate'
        }
        /// <summary>
        /// Test the property 'EstimatedCost'
        /// </summary>
        [TestMethod]
        public void EstimatedCostTest()
        {
            // TODO unit test for the property 'EstimatedCost'
        }
        /// <summary>
        /// Test the property 'UseThisCostWhenOrdering'
        /// </summary>
        [TestMethod]
        public void UseThisCostWhenOrderingTest()
        {
            // TODO unit test for the property 'UseThisCostWhenOrdering'
        }
        /// <summary>
        /// Test the property 'AllowPriceLessThanCost'
        /// </summary>
        [TestMethod]
        public void AllowPriceLessThanCostTest()
        {
            // TODO unit test for the property 'AllowPriceLessThanCost'
        }
        /// <summary>
        /// Test the property 'AllowQuantityLessThanOrdered'
        /// </summary>
        [TestMethod]
        public void AllowQuantityLessThanOrderedTest()
        {
            // TODO unit test for the property 'AllowQuantityLessThanOrdered'
        }

    }

}
