/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebAccountMarketingDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebAccountMarketingDetailTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebAccountMarketingDetail
        //private TsiWebAccountMarketingDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebAccountMarketingDetail
            //instance = new TsiWebAccountMarketingDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebAccountMarketingDetail
        /// </summary>
        [TestMethod]
        public void TsiWebAccountMarketingDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebAccountMarketingDetail
            //Assert.IsInstanceOfType<TsiWebAccountMarketingDetail> (instance, "variable 'instance' is a TsiWebAccountMarketingDetail");
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [TestMethod]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'SourceChangedDate'
        /// </summary>
        [TestMethod]
        public void SourceChangedDateTest()
        {
            // TODO unit test for the property 'SourceChangedDate'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [TestMethod]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'SalesVolume'
        /// </summary>
        [TestMethod]
        public void SalesVolumeTest()
        {
            // TODO unit test for the property 'SalesVolume'
        }
        /// <summary>
        /// Test the property 'NumberOfEmployees'
        /// </summary>
        [TestMethod]
        public void NumberOfEmployeesTest()
        {
            // TODO unit test for the property 'NumberOfEmployees'
        }

    }

}
