/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebServiceOrderItemServicedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebServiceOrderItemServicedResponseTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebServiceOrderItemServicedResponse
        //private TsiWebServiceOrderItemServicedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebServiceOrderItemServicedResponse
            //instance = new TsiWebServiceOrderItemServicedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebServiceOrderItemServicedResponse
        /// </summary>
        [TestMethod]
        public void TsiWebServiceOrderItemServicedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebServiceOrderItemServicedResponse
            //Assert.IsInstanceOfType<TsiWebServiceOrderItemServicedResponse> (instance, "variable 'instance' is a TsiWebServiceOrderItemServicedResponse");
        }


        /// <summary>
        /// Test the property 'ItemServiced'
        /// </summary>
        [TestMethod]
        public void ItemServicedTest()
        {
            // TODO unit test for the property 'ItemServiced'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [TestMethod]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [TestMethod]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
