/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebSearchCriteria
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebSearchCriteriaTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebSearchCriteria
        //private TsiWebSearchCriteria instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebSearchCriteria
            //instance = new TsiWebSearchCriteria();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebSearchCriteria
        /// </summary>
        [TestMethod]
        public void TsiWebSearchCriteriaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebSearchCriteria
            //Assert.IsInstanceOfType<TsiWebSearchCriteria> (instance, "variable 'instance' is a TsiWebSearchCriteria");
        }


        /// <summary>
        /// Test the property 'SearchType'
        /// </summary>
        [TestMethod]
        public void SearchTypeTest()
        {
            // TODO unit test for the property 'SearchType'
        }
        /// <summary>
        /// Test the property 'MatchType'
        /// </summary>
        [TestMethod]
        public void MatchTypeTest()
        {
            // TODO unit test for the property 'MatchType'
        }
        /// <summary>
        /// Test the property 'Criteria'
        /// </summary>
        [TestMethod]
        public void CriteriaTest()
        {
            // TODO unit test for the property 'Criteria'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [TestMethod]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'CustomFieldName'
        /// </summary>
        [TestMethod]
        public void CustomFieldNameTest()
        {
            // TODO unit test for the property 'CustomFieldName'
        }

    }

}
