/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebExternalProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebExternalProductTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebExternalProduct
        //private TsiWebExternalProduct instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebExternalProduct
            //instance = new TsiWebExternalProduct();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebExternalProduct
        /// </summary>
        [TestMethod]
        public void TsiWebExternalProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebExternalProduct
            //Assert.IsInstanceOfType<TsiWebExternalProduct> (instance, "variable 'instance' is a TsiWebExternalProduct");
        }


        /// <summary>
        /// Test the property 'ExternalProductId'
        /// </summary>
        [TestMethod]
        public void ExternalProductIdTest()
        {
            // TODO unit test for the property 'ExternalProductId'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [TestMethod]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [TestMethod]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }
        /// <summary>
        /// Test the property 'SystemEntry'
        /// </summary>
        [TestMethod]
        public void SystemEntryTest()
        {
            // TODO unit test for the property 'SystemEntry'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [TestMethod]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

    }

}
