/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebTaskDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebTaskDetailTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebTaskDetail
        //private TsiWebTaskDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebTaskDetail
            //instance = new TsiWebTaskDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebTaskDetail
        /// </summary>
        [TestMethod]
        public void TsiWebTaskDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebTaskDetail
            //Assert.IsInstanceOfType<TsiWebTaskDetail> (instance, "variable 'instance' is a TsiWebTaskDetail");
        }


        /// <summary>
        /// Test the property 'TaskNumber'
        /// </summary>
        [TestMethod]
        public void TaskNumberTest()
        {
            // TODO unit test for the property 'TaskNumber'
        }
        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [TestMethod]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [TestMethod]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [TestMethod]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'ScheduledForRep'
        /// </summary>
        [TestMethod]
        public void ScheduledForRepTest()
        {
            // TODO unit test for the property 'ScheduledForRep'
        }
        /// <summary>
        /// Test the property 'ScheduledByRep'
        /// </summary>
        [TestMethod]
        public void ScheduledByRepTest()
        {
            // TODO unit test for the property 'ScheduledByRep'
        }
        /// <summary>
        /// Test the property 'ProjectName'
        /// </summary>
        [TestMethod]
        public void ProjectNameTest()
        {
            // TODO unit test for the property 'ProjectName'
        }
        /// <summary>
        /// Test the property 'ProjectPhase'
        /// </summary>
        [TestMethod]
        public void ProjectPhaseTest()
        {
            // TODO unit test for the property 'ProjectPhase'
        }
        /// <summary>
        /// Test the property 'ProjectSubPhase'
        /// </summary>
        [TestMethod]
        public void ProjectSubPhaseTest()
        {
            // TODO unit test for the property 'ProjectSubPhase'
        }
        /// <summary>
        /// Test the property 'ServiceOrderDescription'
        /// </summary>
        [TestMethod]
        public void ServiceOrderDescriptionTest()
        {
            // TODO unit test for the property 'ServiceOrderDescription'
        }
        /// <summary>
        /// Test the property 'QuoteDescription'
        /// </summary>
        [TestMethod]
        public void QuoteDescriptionTest()
        {
            // TODO unit test for the property 'QuoteDescription'
        }
        /// <summary>
        /// Test the property 'OpportunityName'
        /// </summary>
        [TestMethod]
        public void OpportunityNameTest()
        {
            // TODO unit test for the property 'OpportunityName'
        }
        /// <summary>
        /// Test the property 'TaskChecklist'
        /// </summary>
        [TestMethod]
        public void TaskChecklistTest()
        {
            // TODO unit test for the property 'TaskChecklist'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [TestMethod]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

    }

}
