/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPerson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPersonTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPerson
        //private TsiWebPerson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPerson
            //instance = new TsiWebPerson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPerson
        /// </summary>
        [TestMethod]
        public void TsiWebPersonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPerson
            //Assert.IsInstanceOfType<TsiWebPerson> (instance, "variable 'instance' is a TsiWebPerson");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [TestMethod]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [TestMethod]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [TestMethod]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [TestMethod]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [TestMethod]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [TestMethod]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'SearchName'
        /// </summary>
        [TestMethod]
        public void SearchNameTest()
        {
            // TODO unit test for the property 'SearchName'
        }

    }

}
