/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebAssemblyItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebAssemblyItemTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebAssemblyItem
        //private TsiWebAssemblyItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebAssemblyItem
            //instance = new TsiWebAssemblyItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebAssemblyItem
        /// </summary>
        [TestMethod]
        public void TsiWebAssemblyItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebAssemblyItem
            //Assert.IsInstanceOfType<TsiWebAssemblyItem> (instance, "variable 'instance' is a TsiWebAssemblyItem");
        }


        /// <summary>
        /// Test the property 'PriceBookNumber'
        /// </summary>
        [TestMethod]
        public void PriceBookNumberTest()
        {
            // TODO unit test for the property 'PriceBookNumber'
        }
        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [TestMethod]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [TestMethod]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'PrintOnQuote'
        /// </summary>
        [TestMethod]
        public void PrintOnQuoteTest()
        {
            // TODO unit test for the property 'PrintOnQuote'
        }

    }

}
