/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdateExpensePaymentTypeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdateExpensePaymentTypeRequestTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdateExpensePaymentTypeRequest
        //private TsiWebUpdateExpensePaymentTypeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdateExpensePaymentTypeRequest
            //instance = new TsiWebUpdateExpensePaymentTypeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdateExpensePaymentTypeRequest
        /// </summary>
        [TestMethod]
        public void TsiWebUpdateExpensePaymentTypeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdateExpensePaymentTypeRequest
            //Assert.IsInstanceOfType<TsiWebUpdateExpensePaymentTypeRequest> (instance, "variable 'instance' is a TsiWebUpdateExpensePaymentTypeRequest");
        }


        /// <summary>
        /// Test the property 'ExistingExpensePaymentType'
        /// </summary>
        [TestMethod]
        public void ExistingExpensePaymentTypeTest()
        {
            // TODO unit test for the property 'ExistingExpensePaymentType'
        }
        /// <summary>
        /// Test the property 'NewExpensePaymentTypeDescription'
        /// </summary>
        [TestMethod]
        public void NewExpensePaymentTypeDescriptionTest()
        {
            // TODO unit test for the property 'NewExpensePaymentTypeDescription'
        }

    }

}
