/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPurchaseOrderLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPurchaseOrderLineItemTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPurchaseOrderLineItem
        //private TsiWebPurchaseOrderLineItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPurchaseOrderLineItem
            //instance = new TsiWebPurchaseOrderLineItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPurchaseOrderLineItem
        /// </summary>
        [TestMethod]
        public void TsiWebPurchaseOrderLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPurchaseOrderLineItem
            //Assert.IsInstanceOfType<TsiWebPurchaseOrderLineItem> (instance, "variable 'instance' is a TsiWebPurchaseOrderLineItem");
        }


        /// <summary>
        /// Test the property 'PurchaseOrderLineItemNumber'
        /// </summary>
        [TestMethod]
        public void PurchaseOrderLineItemNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderLineItemNumber'
        }
        /// <summary>
        /// Test the property 'LineNumber'
        /// </summary>
        [TestMethod]
        public void LineNumberTest()
        {
            // TODO unit test for the property 'LineNumber'
        }
        /// <summary>
        /// Test the property 'ItemID'
        /// </summary>
        [TestMethod]
        public void ItemIDTest()
        {
            // TODO unit test for the property 'ItemID'
        }
        /// <summary>
        /// Test the property 'ItemDescription'
        /// </summary>
        [TestMethod]
        public void ItemDescriptionTest()
        {
            // TODO unit test for the property 'ItemDescription'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [TestMethod]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'VendorItemNumber'
        /// </summary>
        [TestMethod]
        public void VendorItemNumberTest()
        {
            // TODO unit test for the property 'VendorItemNumber'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasure'
        /// </summary>
        [TestMethod]
        public void UnitOfMeasureTest()
        {
            // TODO unit test for the property 'UnitOfMeasure'
        }
        /// <summary>
        /// Test the property 'ReceivingLocation'
        /// </summary>
        [TestMethod]
        public void ReceivingLocationTest()
        {
            // TODO unit test for the property 'ReceivingLocation'
        }
        /// <summary>
        /// Test the property 'QuantityOrdered'
        /// </summary>
        [TestMethod]
        public void QuantityOrderedTest()
        {
            // TODO unit test for the property 'QuantityOrdered'
        }
        /// <summary>
        /// Test the property 'ProjectedCost'
        /// </summary>
        [TestMethod]
        public void ProjectedCostTest()
        {
            // TODO unit test for the property 'ProjectedCost'
        }
        /// <summary>
        /// Test the property 'TotalProjectedCost'
        /// </summary>
        [TestMethod]
        public void TotalProjectedCostTest()
        {
            // TODO unit test for the property 'TotalProjectedCost'
        }
        /// <summary>
        /// Test the property 'IsRepair'
        /// </summary>
        [TestMethod]
        public void IsRepairTest()
        {
            // TODO unit test for the property 'IsRepair'
        }
        /// <summary>
        /// Test the property 'UnitOfValue'
        /// </summary>
        [TestMethod]
        public void UnitOfValueTest()
        {
            // TODO unit test for the property 'UnitOfValue'
        }
        /// <summary>
        /// Test the property 'ReceivedCost'
        /// </summary>
        [TestMethod]
        public void ReceivedCostTest()
        {
            // TODO unit test for the property 'ReceivedCost'
        }
        /// <summary>
        /// Test the property 'QuantityCancelled'
        /// </summary>
        [TestMethod]
        public void QuantityCancelledTest()
        {
            // TODO unit test for the property 'QuantityCancelled'
        }
        /// <summary>
        /// Test the property 'Stock'
        /// </summary>
        [TestMethod]
        public void StockTest()
        {
            // TODO unit test for the property 'Stock'
        }
        /// <summary>
        /// Test the property 'DistributionFlag'
        /// </summary>
        [TestMethod]
        public void DistributionFlagTest()
        {
            // TODO unit test for the property 'DistributionFlag'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [TestMethod]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'CancelledComment'
        /// </summary>
        [TestMethod]
        public void CancelledCommentTest()
        {
            // TODO unit test for the property 'CancelledComment'
        }
        /// <summary>
        /// Test the property 'ExpectedDate'
        /// </summary>
        [TestMethod]
        public void ExpectedDateTest()
        {
            // TODO unit test for the property 'ExpectedDate'
        }
        /// <summary>
        /// Test the property 'GLCode'
        /// </summary>
        [TestMethod]
        public void GLCodeTest()
        {
            // TODO unit test for the property 'GLCode'
        }
        /// <summary>
        /// Test the property 'CaseItemID'
        /// </summary>
        [TestMethod]
        public void CaseItemIDTest()
        {
            // TODO unit test for the property 'CaseItemID'
        }
        /// <summary>
        /// Test the property 'CaseItemDescription'
        /// </summary>
        [TestMethod]
        public void CaseItemDescriptionTest()
        {
            // TODO unit test for the property 'CaseItemDescription'
        }
        /// <summary>
        /// Test the property 'CaseUnitOfMeasure'
        /// </summary>
        [TestMethod]
        public void CaseUnitOfMeasureTest()
        {
            // TODO unit test for the property 'CaseUnitOfMeasure'
        }
        /// <summary>
        /// Test the property 'DisplayQuantityOrdered'
        /// </summary>
        [TestMethod]
        public void DisplayQuantityOrderedTest()
        {
            // TODO unit test for the property 'DisplayQuantityOrdered'
        }
        /// <summary>
        /// Test the property 'CaseUnitCost'
        /// </summary>
        [TestMethod]
        public void CaseUnitCostTest()
        {
            // TODO unit test for the property 'CaseUnitCost'
        }
        /// <summary>
        /// Test the property 'IsCaseOrder'
        /// </summary>
        [TestMethod]
        public void IsCaseOrderTest()
        {
            // TODO unit test for the property 'IsCaseOrder'
        }
        /// <summary>
        /// Test the property 'UpdateBaseCostAndSellPrices'
        /// </summary>
        [TestMethod]
        public void UpdateBaseCostAndSellPricesTest()
        {
            // TODO unit test for the property 'UpdateBaseCostAndSellPrices'
        }
        /// <summary>
        /// Test the property 'IsClosedAssembly'
        /// </summary>
        [TestMethod]
        public void IsClosedAssemblyTest()
        {
            // TODO unit test for the property 'IsClosedAssembly'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [TestMethod]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UpdateVendorCost'
        /// </summary>
        [TestMethod]
        public void UpdateVendorCostTest()
        {
            // TODO unit test for the property 'UpdateVendorCost'
        }
        /// <summary>
        /// Test the property 'ReceivingBin'
        /// </summary>
        [TestMethod]
        public void ReceivingBinTest()
        {
            // TODO unit test for the property 'ReceivingBin'
        }
        /// <summary>
        /// Test the property 'SerialNumbers'
        /// </summary>
        [TestMethod]
        public void SerialNumbersTest()
        {
            // TODO unit test for the property 'SerialNumbers'
        }
        /// <summary>
        /// Test the property 'LineItemReceipts'
        /// </summary>
        [TestMethod]
        public void LineItemReceiptsTest()
        {
            // TODO unit test for the property 'LineItemReceipts'
        }
        /// <summary>
        /// Test the property 'Assembly'
        /// </summary>
        [TestMethod]
        public void AssemblyTest()
        {
            // TODO unit test for the property 'Assembly'
        }

    }

}
