/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdateTimeEntryReasonRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdateTimeEntryReasonRequestTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdateTimeEntryReasonRequest
        //private TsiWebUpdateTimeEntryReasonRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdateTimeEntryReasonRequest
            //instance = new TsiWebUpdateTimeEntryReasonRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdateTimeEntryReasonRequest
        /// </summary>
        [TestMethod]
        public void TsiWebUpdateTimeEntryReasonRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdateTimeEntryReasonRequest
            //Assert.IsInstanceOfType<TsiWebUpdateTimeEntryReasonRequest> (instance, "variable 'instance' is a TsiWebUpdateTimeEntryReasonRequest");
        }


        /// <summary>
        /// Test the property 'NewLogReason'
        /// </summary>
        [TestMethod]
        public void NewLogReasonTest()
        {
            // TODO unit test for the property 'NewLogReason'
        }
        /// <summary>
        /// Test the property 'TimeEntry'
        /// </summary>
        [TestMethod]
        public void TimeEntryTest()
        {
            // TODO unit test for the property 'TimeEntry'
        }
        /// <summary>
        /// Test the property 'RateBasis'
        /// </summary>
        [TestMethod]
        public void RateBasisTest()
        {
            // TODO unit test for the property 'RateBasis'
        }
        /// <summary>
        /// Test the property 'BillingOption'
        /// </summary>
        [TestMethod]
        public void BillingOptionTest()
        {
            // TODO unit test for the property 'BillingOption'
        }
        /// <summary>
        /// Test the property 'UseStandardRate'
        /// </summary>
        [TestMethod]
        public void UseStandardRateTest()
        {
            // TODO unit test for the property 'UseStandardRate'
        }

    }

}
