/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebServiceOrderResolution
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebServiceOrderResolutionTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebServiceOrderResolution
        //private TsiWebServiceOrderResolution instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebServiceOrderResolution
            //instance = new TsiWebServiceOrderResolution();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebServiceOrderResolution
        /// </summary>
        [TestMethod]
        public void TsiWebServiceOrderResolutionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebServiceOrderResolution
            //Assert.IsInstanceOfType<TsiWebServiceOrderResolution> (instance, "variable 'instance' is a TsiWebServiceOrderResolution");
        }


        /// <summary>
        /// Test the property 'Resolution'
        /// </summary>
        [TestMethod]
        public void ResolutionTest()
        {
            // TODO unit test for the property 'Resolution'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [TestMethod]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

    }

}
