/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPurchaseOrderLineItemSerialNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPurchaseOrderLineItemSerialNumberTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPurchaseOrderLineItemSerialNumber
        //private TsiWebPurchaseOrderLineItemSerialNumber instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPurchaseOrderLineItemSerialNumber
            //instance = new TsiWebPurchaseOrderLineItemSerialNumber();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPurchaseOrderLineItemSerialNumber
        /// </summary>
        [TestMethod]
        public void TsiWebPurchaseOrderLineItemSerialNumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPurchaseOrderLineItemSerialNumber
            //Assert.IsInstanceOfType<TsiWebPurchaseOrderLineItemSerialNumber> (instance, "variable 'instance' is a TsiWebPurchaseOrderLineItemSerialNumber");
        }


        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [TestMethod]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [TestMethod]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [TestMethod]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderAssemblyDetailNumber'
        /// </summary>
        [TestMethod]
        public void PurchaseOrderAssemblyDetailNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderAssemblyDetailNumber'
        }
        /// <summary>
        /// Test the property 'Posted'
        /// </summary>
        [TestMethod]
        public void PostedTest()
        {
            // TODO unit test for the property 'Posted'
        }

    }

}
