/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebServiceOrderSubContractor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebServiceOrderSubContractorTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebServiceOrderSubContractor
        //private TsiWebServiceOrderSubContractor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebServiceOrderSubContractor
            //instance = new TsiWebServiceOrderSubContractor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebServiceOrderSubContractor
        /// </summary>
        [TestMethod]
        public void TsiWebServiceOrderSubContractorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebServiceOrderSubContractor
            //Assert.IsInstanceOfType<TsiWebServiceOrderSubContractor> (instance, "variable 'instance' is a TsiWebServiceOrderSubContractor");
        }


        /// <summary>
        /// Test the property 'AssignedSubContractorID'
        /// </summary>
        [TestMethod]
        public void AssignedSubContractorIDTest()
        {
            // TODO unit test for the property 'AssignedSubContractorID'
        }
        /// <summary>
        /// Test the property 'ServiceOrderNumber'
        /// </summary>
        [TestMethod]
        public void ServiceOrderNumberTest()
        {
            // TODO unit test for the property 'ServiceOrderNumber'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [TestMethod]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [TestMethod]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'Responsibility'
        /// </summary>
        [TestMethod]
        public void ResponsibilityTest()
        {
            // TODO unit test for the property 'Responsibility'
        }
        /// <summary>
        /// Test the property 'ProjectedStartDate'
        /// </summary>
        [TestMethod]
        public void ProjectedStartDateTest()
        {
            // TODO unit test for the property 'ProjectedStartDate'
        }
        /// <summary>
        /// Test the property 'ActualStartDate'
        /// </summary>
        [TestMethod]
        public void ActualStartDateTest()
        {
            // TODO unit test for the property 'ActualStartDate'
        }
        /// <summary>
        /// Test the property 'ProjectedCompletionDate'
        /// </summary>
        [TestMethod]
        public void ProjectedCompletionDateTest()
        {
            // TODO unit test for the property 'ProjectedCompletionDate'
        }
        /// <summary>
        /// Test the property 'ActualCompleteDate'
        /// </summary>
        [TestMethod]
        public void ActualCompleteDateTest()
        {
            // TODO unit test for the property 'ActualCompleteDate'
        }
        /// <summary>
        /// Test the property 'BidPrice'
        /// </summary>
        [TestMethod]
        public void BidPriceTest()
        {
            // TODO unit test for the property 'BidPrice'
        }
        /// <summary>
        /// Test the property 'ActualPrice'
        /// </summary>
        [TestMethod]
        public void ActualPriceTest()
        {
            // TODO unit test for the property 'ActualPrice'
        }
        /// <summary>
        /// Test the property 'WorkRequested'
        /// </summary>
        [TestMethod]
        public void WorkRequestedTest()
        {
            // TODO unit test for the property 'WorkRequested'
        }
        /// <summary>
        /// Test the property 'WorkAgreementInPlace'
        /// </summary>
        [TestMethod]
        public void WorkAgreementInPlaceTest()
        {
            // TODO unit test for the property 'WorkAgreementInPlace'
        }
        /// <summary>
        /// Test the property 'SubContractorGetsPermits'
        /// </summary>
        [TestMethod]
        public void SubContractorGetsPermitsTest()
        {
            // TODO unit test for the property 'SubContractorGetsPermits'
        }
        /// <summary>
        /// Test the property 'FieldReportsCurrent'
        /// </summary>
        [TestMethod]
        public void FieldReportsCurrentTest()
        {
            // TODO unit test for the property 'FieldReportsCurrent'
        }

    }

}
