/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebUpdatePriceBookItemModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebUpdatePriceBookItemModelTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebUpdatePriceBookItemModel
        //private TsiWebUpdatePriceBookItemModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebUpdatePriceBookItemModel
            //instance = new TsiWebUpdatePriceBookItemModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebUpdatePriceBookItemModel
        /// </summary>
        [TestMethod]
        public void TsiWebUpdatePriceBookItemModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebUpdatePriceBookItemModel
            //Assert.IsInstanceOfType<TsiWebUpdatePriceBookItemModel> (instance, "variable 'instance' is a TsiWebUpdatePriceBookItemModel");
        }


        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [TestMethod]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [TestMethod]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }

    }

}
