/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPricingDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPricingDetailTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPricingDetail
        //private TsiWebPricingDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPricingDetail
            //instance = new TsiWebPricingDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPricingDetail
        /// </summary>
        [TestMethod]
        public void TsiWebPricingDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPricingDetail
            //Assert.IsInstanceOfType<TsiWebPricingDetail> (instance, "variable 'instance' is a TsiWebPricingDetail");
        }


        /// <summary>
        /// Test the property 'PriceLevel'
        /// </summary>
        [TestMethod]
        public void PriceLevelTest()
        {
            // TODO unit test for the property 'PriceLevel'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [TestMethod]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PriceOverride'
        /// </summary>
        [TestMethod]
        public void PriceOverrideTest()
        {
            // TODO unit test for the property 'PriceOverride'
        }
        /// <summary>
        /// Test the property 'SellingPrice'
        /// </summary>
        [TestMethod]
        public void SellingPriceTest()
        {
            // TODO unit test for the property 'SellingPrice'
        }
        /// <summary>
        /// Test the property 'Markup'
        /// </summary>
        [TestMethod]
        public void MarkupTest()
        {
            // TODO unit test for the property 'Markup'
        }
        /// <summary>
        /// Test the property 'Markdown'
        /// </summary>
        [TestMethod]
        public void MarkdownTest()
        {
            // TODO unit test for the property 'Markdown'
        }
        /// <summary>
        /// Test the property 'Margin'
        /// </summary>
        [TestMethod]
        public void MarginTest()
        {
            // TODO unit test for the property 'Margin'
        }
        /// <summary>
        /// Test the property 'FlatPrice'
        /// </summary>
        [TestMethod]
        public void FlatPriceTest()
        {
            // TODO unit test for the property 'FlatPrice'
        }
        /// <summary>
        /// Test the property 'RepairLevel'
        /// </summary>
        [TestMethod]
        public void RepairLevelTest()
        {
            // TODO unit test for the property 'RepairLevel'
        }
        /// <summary>
        /// Test the property 'CostToUse'
        /// </summary>
        [TestMethod]
        public void CostToUseTest()
        {
            // TODO unit test for the property 'CostToUse'
        }
        /// <summary>
        /// Test the property 'PriceLevelCategoryName'
        /// </summary>
        [TestMethod]
        public void PriceLevelCategoryNameTest()
        {
            // TODO unit test for the property 'PriceLevelCategoryName'
        }
        /// <summary>
        /// Test the property 'GlCodeOverride'
        /// </summary>
        [TestMethod]
        public void GlCodeOverrideTest()
        {
            // TODO unit test for the property 'GlCodeOverride'
        }
        /// <summary>
        /// Test the property 'IncomeGlCode'
        /// </summary>
        [TestMethod]
        public void IncomeGlCodeTest()
        {
            // TODO unit test for the property 'IncomeGlCode'
        }
        /// <summary>
        /// Test the property 'CostGlCode'
        /// </summary>
        [TestMethod]
        public void CostGlCodeTest()
        {
            // TODO unit test for the property 'CostGlCode'
        }

    }

}
