/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.VisualStudio.TestTools.UnitTesting;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tsi.Web.Api;
using Tsi.Web.Model;
using Tsi.Web.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TsiWebPagedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestClass]
    public class TsiWebPagedRequestTests
    {
        // TODO uncomment below to declare an instance variable for TsiWebPagedRequest
        //private TsiWebPagedRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            // TODO uncomment below to create an instance of TsiWebPagedRequest
            //instance = new TsiWebPagedRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TsiWebPagedRequest
        /// </summary>
        [TestMethod]
        public void TsiWebPagedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TsiWebPagedRequest
            //Assert.IsInstanceOfType<TsiWebPagedRequest> (instance, "variable 'instance' is a TsiWebPagedRequest");
        }


        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [TestMethod]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'StartRow'
        /// </summary>
        [TestMethod]
        public void StartRowTest()
        {
            // TODO unit test for the property 'StartRow'
        }

    }

}
