/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tsi.Web.Client.SwaggerDateConverter;

namespace Tsi.Web.Model
{
    /// <summary>
    /// TsiWebDispatchBoard
    /// </summary>
    [DataContract]
    public partial class TsiWebDispatchBoard :  IEquatable<TsiWebDispatchBoard>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TsiWebDispatchBoard" /> class.
        /// </summary>
        /// <param name="dispatchBoardId">dispatchBoardId.</param>
        /// <param name="description">description.</param>
        public TsiWebDispatchBoard(int? dispatchBoardId = default(int?), string description = default(string))
        {
            this.DispatchBoardId = dispatchBoardId;
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets DispatchBoardId
        /// </summary>
        [DataMember(Name="DispatchBoardId", EmitDefaultValue=false)]
        public int? DispatchBoardId { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TsiWebDispatchBoard {\n");
            sb.Append("  DispatchBoardId: ").Append(DispatchBoardId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TsiWebDispatchBoard);
        }

        /// <summary>
        /// Returns true if TsiWebDispatchBoard instances are equal
        /// </summary>
        /// <param name="input">Instance of TsiWebDispatchBoard to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TsiWebDispatchBoard input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DispatchBoardId == input.DispatchBoardId ||
                    (this.DispatchBoardId != null &&
                    this.DispatchBoardId.Equals(input.DispatchBoardId))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DispatchBoardId != null)
                    hashCode = hashCode * 59 + this.DispatchBoardId.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
