/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tsi.Web.Client.SwaggerDateConverter;

namespace Tsi.Web.Model
{
    /// <summary>
    /// TsiWebAssignedSICCode
    /// </summary>
    [DataContract]
    public partial class TsiWebAssignedSICCode :  IEquatable<TsiWebAssignedSICCode>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TsiWebAssignedSICCode" /> class.
        /// </summary>
        /// <param name="sICCode">sICCode.</param>
        /// <param name="lastModified">lastModified.</param>
        public TsiWebAssignedSICCode(string sICCode = default(string), DateTime? lastModified = default(DateTime?))
        {
            this.SICCode = sICCode;
            this.LastModified = lastModified;
        }
        
        /// <summary>
        /// Gets or Sets SICCode
        /// </summary>
        [DataMember(Name="SICCode", EmitDefaultValue=false)]
        public string SICCode { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name="LastModified", EmitDefaultValue=false)]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TsiWebAssignedSICCode {\n");
            sb.Append("  SICCode: ").Append(SICCode).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TsiWebAssignedSICCode);
        }

        /// <summary>
        /// Returns true if TsiWebAssignedSICCode instances are equal
        /// </summary>
        /// <param name="input">Instance of TsiWebAssignedSICCode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TsiWebAssignedSICCode input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SICCode == input.SICCode ||
                    (this.SICCode != null &&
                    this.SICCode.Equals(input.SICCode))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SICCode != null)
                    hashCode = hashCode * 59 + this.SICCode.GetHashCode();
                if (this.LastModified != null)
                    hashCode = hashCode * 59 + this.LastModified.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
