/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tsi.Web.Client.SwaggerDateConverter;

namespace Tsi.Web.Model
{
    /// <summary>
    /// TsiWebTimeSlipSummary
    /// </summary>
    [DataContract]
    public partial class TsiWebTimeSlipSummary :  IEquatable<TsiWebTimeSlipSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TsiWebTimeSlipSummary" /> class.
        /// </summary>
        /// <param name="timeSlip">timeSlip.</param>
        /// <param name="techAssignedRep">techAssignedRep.</param>
        /// <param name="acceptedOrRejectedByRep">acceptedOrRejectedByRep.</param>
        public TsiWebTimeSlipSummary(TsiWebTimeSlip timeSlip = default(TsiWebTimeSlip), TsiWebPerson techAssignedRep = default(TsiWebPerson), TsiWebPerson acceptedOrRejectedByRep = default(TsiWebPerson))
        {
            this.TimeSlip = timeSlip;
            this.TechAssignedRep = techAssignedRep;
            this.AcceptedOrRejectedByRep = acceptedOrRejectedByRep;
        }
        
        /// <summary>
        /// Gets or Sets TimeSlip
        /// </summary>
        [DataMember(Name="TimeSlip", EmitDefaultValue=false)]
        public TsiWebTimeSlip TimeSlip { get; set; }

        /// <summary>
        /// Gets or Sets TechAssignedRep
        /// </summary>
        [DataMember(Name="TechAssignedRep", EmitDefaultValue=false)]
        public TsiWebPerson TechAssignedRep { get; set; }

        /// <summary>
        /// Gets or Sets AcceptedOrRejectedByRep
        /// </summary>
        [DataMember(Name="AcceptedOrRejectedByRep", EmitDefaultValue=false)]
        public TsiWebPerson AcceptedOrRejectedByRep { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TsiWebTimeSlipSummary {\n");
            sb.Append("  TimeSlip: ").Append(TimeSlip).Append("\n");
            sb.Append("  TechAssignedRep: ").Append(TechAssignedRep).Append("\n");
            sb.Append("  AcceptedOrRejectedByRep: ").Append(AcceptedOrRejectedByRep).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TsiWebTimeSlipSummary);
        }

        /// <summary>
        /// Returns true if TsiWebTimeSlipSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of TsiWebTimeSlipSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TsiWebTimeSlipSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TimeSlip == input.TimeSlip ||
                    (this.TimeSlip != null &&
                    this.TimeSlip.Equals(input.TimeSlip))
                ) && 
                (
                    this.TechAssignedRep == input.TechAssignedRep ||
                    (this.TechAssignedRep != null &&
                    this.TechAssignedRep.Equals(input.TechAssignedRep))
                ) && 
                (
                    this.AcceptedOrRejectedByRep == input.AcceptedOrRejectedByRep ||
                    (this.AcceptedOrRejectedByRep != null &&
                    this.AcceptedOrRejectedByRep.Equals(input.AcceptedOrRejectedByRep))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeSlip != null)
                    hashCode = hashCode * 59 + this.TimeSlip.GetHashCode();
                if (this.TechAssignedRep != null)
                    hashCode = hashCode * 59 + this.TechAssignedRep.GetHashCode();
                if (this.AcceptedOrRejectedByRep != null)
                    hashCode = hashCode * 59 + this.AcceptedOrRejectedByRep.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
