/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Tsi.Web.Client.SwaggerDateConverter;

namespace Tsi.Web.Model
{
    /// <summary>
    /// TsiWebServiceOrderSeverity
    /// </summary>
    [DataContract]
    public partial class TsiWebServiceOrderSeverity :  IEquatable<TsiWebServiceOrderSeverity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TsiWebServiceOrderSeverity" /> class.
        /// </summary>
        /// <param name="serviceOrderSeverityNumber">serviceOrderSeverityNumber.</param>
        /// <param name="severity">severity.</param>
        /// <param name="rank">rank.</param>
        public TsiWebServiceOrderSeverity(int? serviceOrderSeverityNumber = default(int?), string severity = default(string), int? rank = default(int?))
        {
            this.ServiceOrderSeverityNumber = serviceOrderSeverityNumber;
            this.Severity = severity;
            this.Rank = rank;
        }
        
        /// <summary>
        /// Gets or Sets ServiceOrderSeverityNumber
        /// </summary>
        [DataMember(Name="ServiceOrderSeverityNumber", EmitDefaultValue=false)]
        public int? ServiceOrderSeverityNumber { get; set; }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [DataMember(Name="Severity", EmitDefaultValue=false)]
        public string Severity { get; set; }

        /// <summary>
        /// Gets or Sets Rank
        /// </summary>
        [DataMember(Name="Rank", EmitDefaultValue=false)]
        public int? Rank { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TsiWebServiceOrderSeverity {\n");
            sb.Append("  ServiceOrderSeverityNumber: ").Append(ServiceOrderSeverityNumber).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TsiWebServiceOrderSeverity);
        }

        /// <summary>
        /// Returns true if TsiWebServiceOrderSeverity instances are equal
        /// </summary>
        /// <param name="input">Instance of TsiWebServiceOrderSeverity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TsiWebServiceOrderSeverity input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServiceOrderSeverityNumber == input.ServiceOrderSeverityNumber ||
                    (this.ServiceOrderSeverityNumber != null &&
                    this.ServiceOrderSeverityNumber.Equals(input.ServiceOrderSeverityNumber))
                ) && 
                (
                    this.Severity == input.Severity ||
                    (this.Severity != null &&
                    this.Severity.Equals(input.Severity))
                ) && 
                (
                    this.Rank == input.Rank ||
                    (this.Rank != null &&
                    this.Rank.Equals(input.Rank))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServiceOrderSeverityNumber != null)
                    hashCode = hashCode * 59 + this.ServiceOrderSeverityNumber.GetHashCode();
                if (this.Severity != null)
                    hashCode = hashCode * 59 + this.Severity.GetHashCode();
                if (this.Rank != null)
                    hashCode = hashCode * 59 + this.Rank.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
