/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Tsi.Web.Client;
using Tsi.Web.Api;
using Tsi.Web.Model;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing RepsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestClass]
    public class RepsApiTests
    {
        private RepsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            instance = new RepsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepsApi
        /// </summary>
        [TestMethod]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RepsApi
            //Assert.IsInstanceOfType(typeof(RepsApi), instance, "instance is a RepsApi");
        }

        
        /// <summary>
        /// Test RepsGetRepCompletedTasks
        /// </summary>
        [TestMethod]
        public void RepsGetRepCompletedTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? repNumber = null;
            //bool? repModelScheduledFor = null;
            //bool? repModelScheduledBy = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.RepsGetRepCompletedTasks(repNumber, repModelScheduledFor, repModelScheduledBy, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebTasksResponse> (response, "response is TsiWebTasksResponse");
        }
        
        /// <summary>
        /// Test RepsGetRepDetail
        /// </summary>
        [TestMethod]
        public void RepsGetRepDetailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? repNumber = null;
            //var response = instance.RepsGetRepDetail(repNumber);
            //Assert.IsInstanceOf<TsiWebRepDetail> (response, "response is TsiWebRepDetail");
        }
        
        /// <summary>
        /// Test RepsGetRepIncompleteTasks
        /// </summary>
        [TestMethod]
        public void RepsGetRepIncompleteTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? repNumber = null;
            //bool? repModelScheduledFor = null;
            //bool? repModelScheduledBy = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.RepsGetRepIncompleteTasks(repNumber, repModelScheduledFor, repModelScheduledBy, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebTasksResponse> (response, "response is TsiWebTasksResponse");
        }
        
        /// <summary>
        /// Test RepsGetRepSummary
        /// </summary>
        [TestMethod]
        public void RepsGetRepSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? repNumber = null;
            //var response = instance.RepsGetRepSummary(repNumber);
            //Assert.IsInstanceOf<TsiWebRepSummary> (response, "response is TsiWebRepSummary");
        }
        
        /// <summary>
        /// Test RepsGetRepTasks
        /// </summary>
        [TestMethod]
        public void RepsGetRepTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? repNumber = null;
            //bool? repModelScheduledFor = null;
            //bool? repModelScheduledBy = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.RepsGetRepTasks(repNumber, repModelScheduledFor, repModelScheduledBy, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebTasksResponse> (response, "response is TsiWebTasksResponse");
        }
        
    }

}
