/* 
 * Tigerpaw API Method Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 18.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Tsi.Web.Client;
using Tsi.Web.Api;
using Tsi.Web.Model;

namespace Tsi.Web.Test
{
    /// <summary>
    ///  Class for testing TimeSlipApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestClass]
    public class TimeSlipApiTests
    {
        private TimeSlipApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [TestInitialize]
        public void Init()
        {
            instance = new TimeSlipApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TestCleanup]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TimeSlipApi
        /// </summary>
        [TestMethod]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TimeSlipApi
            //Assert.IsInstanceOfType(typeof(TimeSlipApi), instance, "instance is a TimeSlipApi");
        }

        
        /// <summary>
        /// Test TimeSlipAdvancedSearch
        /// </summary>
        [TestMethod]
        public void TimeSlipAdvancedSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TsiWebAdvancedSearchRequest request = null;
            //var response = instance.TimeSlipAdvancedSearch(request);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipCreateTimeSlip
        /// </summary>
        [TestMethod]
        public void TimeSlipCreateTimeSlipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TsiWebCreateTimeSlipModel model = null;
            //var response = instance.TimeSlipCreateTimeSlip(model);
            //Assert.IsInstanceOf<TsiWebTimeSlipResponse> (response, "response is TsiWebTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipGetTimeSlip
        /// </summary>
        [TestMethod]
        public void TimeSlipGetTimeSlipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? timeSlipNumber = null;
            //var response = instance.TimeSlipGetTimeSlip(timeSlipNumber);
            //Assert.IsInstanceOf<TsiWebTimeSlipSummary> (response, "response is TsiWebTimeSlipSummary");
        }
        
        /// <summary>
        /// Test TimeSlipSearchByEndDate
        /// </summary>
        [TestMethod]
        public void TimeSlipSearchByEndDateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TsiWebDateTimeSearchModel model = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.TimeSlipSearchByEndDate(model, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipSearchByLogReason
        /// </summary>
        [TestMethod]
        public void TimeSlipSearchByLogReasonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string criteria = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.TimeSlipSearchByLogReason(criteria, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipSearchByStartDate
        /// </summary>
        [TestMethod]
        public void TimeSlipSearchByStartDateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TsiWebDateTimeSearchModel model = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.TimeSlipSearchByStartDate(model, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipSearchByTechAssigned
        /// </summary>
        [TestMethod]
        public void TimeSlipSearchByTechAssignedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string criteria = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.TimeSlipSearchByTechAssigned(criteria, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipSearchByTimeSlipNumber
        /// </summary>
        [TestMethod]
        public void TimeSlipSearchByTimeSlipNumberTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string criteria = null;
            //int? pageRequestPageSize = null;
            //int? pageRequestStartRow = null;
            //var response = instance.TimeSlipSearchByTimeSlipNumber(criteria, pageRequestPageSize, pageRequestStartRow);
            //Assert.IsInstanceOf<TsiWebSearchTimeSlipResponse> (response, "response is TsiWebSearchTimeSlipResponse");
        }
        
        /// <summary>
        /// Test TimeSlipUpdateTimeSlip
        /// </summary>
        [TestMethod]
        public void TimeSlipUpdateTimeSlipTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? timeSlipNumber = null;
            //TsiWebUpdateTimeSlipModel model = null;
            //var response = instance.TimeSlipUpdateTimeSlip(timeSlipNumber, model);
            //Assert.IsInstanceOf<TsiWebTimeSlipResponse> (response, "response is TsiWebTimeSlipResponse");
        }
        
    }

}
